name: Magento 2 Module Unit Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit Tests with PHP ${{ matrix.php-version }} and Magento ${{ matrix.magento-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']
        magento-version: ['2.4.3', '2.4.5']

    env:
      COMPOSER_VERSION: 2.1
      magento-root-dir: magento

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, bcmath
          ini-values: post_max_size=256M, max_execution_time=300
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer Dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Add Mage-OS Repository
        run: composer config repositories.mage-os composer https://mirror.mage-os.org/

      - name: Allow Magento Composer Plugin
        run: composer config --no-plugins allow-plugins.magento/composer-dependency-version-audit-plugin true

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Configure Magento required packages
        run: |
          composer require magento/product-community-edition:${{ matrix.magento-version }} --no-update
          composer update

      - name: Run Unit Tests
        run: |
          vendor/bin/phpunit -c phpunit.xml
